LucilleKarma/Luminance

Core/Graphics/Primitives/IPixelatedPrimitiveRenderer.cs
Core/Graphics/Primitives/PixelationPrimitiveLayer.cs
Core/Graphics/Primitives/PrimitivePixelationSystem.cs
Core/Graphics/Primitives/PrimitiveRenderer.cs
Core/Graphics/Primitives/PrimitiveSettings.cs
Core/Graphics/Primitives/VertexColor2DColorTexture.cs

Port of my system made for Calamity, with some minor improvements.

Implemented the Primitive System

---

Common/Utilities/Drawcode/DrawingUtilities.Spritebatch.cs
Core/Config.cs
Core/Graphics/Atlases/Atlas.cs
Core/Graphics/Atlases/AtlasManager.cs
Core/Graphics/Atlases/AtlasTexture.cs
Core/Graphics/Particles/Particle.cs
Core/Graphics/Particles/ParticleManager.cs
Luminance.cs
en-US.hjson

Added a particle system that uses atlasing + multithreading for performance.

Implemented the Particle System

---

Core/ModCalls/ModCall.cs
Core/ModCalls/ModCallManager.cs

Added the Mod Call system WoTG and Infernum uses, but improved.

Implemented the Mod Call system.

---

Core/ILWrappers/ManagedILEdit.cs
Luminance.cs

Added a version of WoTGs IL wrapper, that manually unloads in the case of edits being applied to other mods.

Implemented the ILEdit Wrappers.

---

Common/StateMachines/StateMachines/PushdownAutomata.cs

Fixed the ordering being incorrect with the event and callback when transitioning states in the state machine..

State Machine Bug Fix

---

Core/Graphics/Particles/Metaballs/MetaballInstance.cs
Core/Graphics/Particles/Metaballs/MetaballManager.cs
Core/Graphics/Particles/Metaballs/MetaballType.cs
Core/Graphics/Particles/ParticleManager.cs

Implemented a version of the WoTG/Calamity metaball system, made a bit easier to use.

Implemented the Metaball System.

---

Core/Graphics/Shaders/ManagedScreenFilter.cs
Core/Graphics/Shaders/ShaderManager.cs

Added ManagedScreenFilter, and made both shaders disposable.

Implemented the ManagedScreenFilter System

---

Core/Graphics/Primitives/PrimitiveRenderer.cs

- Reverted to IEnumerable, as its not very slow here and the ToArray() call is.

Primitive Renderer Performance Tweaks

---

Core/Graphics/Particles/Metaballs/MetaballType.cs

- Made the Textures array be an array of funcs, to allow for dynamic texture swapping.

Metaball Texture Array Fix

---

Core/Cutscenes/Cutscene.cs
Core/Cutscenes/CutsceneManager.cs
Core/Graphics/Shaders/ShaderManager.cs
Core/Graphics/SpecificEffectManagers/ScreenModifierManager.cs

- Added the cutscene system for Infernum, I see this being useful for other mods and have another use case in mind personally.
- Created ScreenModifierManager to handle ordered FilterManager.EndCapture detours. Made the screenfilters use it.

Implemented the Cutscene and ScreenModifierManager system.

---

Core/Graphics/SpecificEffectManagers/BlockerSystem.cs

Added the input/ui blocker from WoTG and Infernum.

Implemented the Blocker System.

---

Common/Easings/EasingCurve.cs
Common/Utilities/Drawcode/DrawingUtilities.HelperMethods.cs
Common/Utilities/Entities/NPCUtilities.cs
Common/Utilities/Entities/ProjectileUtilities.cs
Common/Utilities/Mathematics/CollisionUtilities.cs
Common/Utilities/Mathematics/MathematicalUtilities.AngleCalculations.cs
Common/Utilities/Mathematics/MathematicalUtilities.Pseudorandomness.cs
Common/Utilities/Reflection/ReflectionUtilities.cs
Common/Utilities/TextUtilities.cs
Core/Graphics/Shaders/ShaderManager.cs
Core/LuminanceSystem.cs
Luminance.cs

- Also combined the shader and atlas loading, and made it fully automatic.

Added more Utils for Infernum.

---

Core/Graphics/Particles/Metaballs/MetaballInstance.cs
Core/Graphics/Particles/Metaballs/MetaballType.cs

- Changes to allow Infernum to work as intended.

Added a public constructor + IEnumerable create method.

---

Common/Utilities/Drawcode/DrawingUtilities.HelperMethods.cs
Core/Config.cs
Core/Graphics/Particles/ManualParticleRenderer.cs
Core/Graphics/Particles/Particle.cs
Core/Graphics/Particles/ParticleManager.cs
Core/Graphics/Shaders/ShaderManager.cs
Luminance.cs

- Added a class that allows for finer control over particle rendering, for use cases where particles are representing more complex things than just moving entities with a simple texture and more advanced rendering is required.

Implemented the ManualParticleRenderer system.

---

Common/Utilities/Drawcode/DrawingUtilities.HelperMethods.cs
Core/Config.cs
Core/Hooking/HookHelper.cs
Core/Hooking/ICustomDetourProvider.cs
Core/Hooking/IExistingDetourProvider.cs
Core/Hooking/ILEditProvider.cs
Core/Hooking/ManagedILEdit.cs
Core/LuminanceSystem.cs
Luminance.cs

- Added more helpers for performing iL Edits and existing + custom detouring.

Improved Hook Helpers.

---

Core/Balancing/BalancePriority.cs
Core/Balancing/BalancingManager.cs
Core/Balancing/DefaultNPCBalancingRules.cs
Core/Balancing/INPCHitBalancingRule.cs
Core/Balancing/InternalBalancingManager.cs
Core/Balancing/ItemBalancingChange.cs
Core/Balancing/NPCHPBalancingChange.cs
Core/Balancing/NPCHitBalancingChange.cs
Core/Balancing/NPCHitContext.cs
Core/Globals/LuminanceGlobalItem.cs
Core/Globals/LuminanceGlobalNPC.cs

- Added a NPC/Item balancing system, that has fairly simple mod combability.

Implemented the Balancing System

---

Core/Graphics/Shaders/ShaderManager.cs

- Fixed stupid main thread error.

Unload fixes

---

Localization/zh-Hans_Mods.Luminance.hjson

I found out that infernum and fargosouls will depend on this mod, so I think localization is necessary. My discord name is mada, you can easily find me on infernum or fargo discord

zh localization

---

Common/DataStructures/IProjOwnedByBoss.cs
Common/Utilities/Entities/NPCUtilities.cs
Common/Utilities/Entities/ProjectileUtilities.cs
Core/Graphics/Primitives/PrimitivePixelationSystem.cs

Reduces the need for checking and fixes potential bugs introduced by iterating over the final array value (not needed here since such a check already exists but is generally good practice). It's also technically faster, but not that important.
I also left a comment under one of the methods discussing a potential optimization that I've yet to benchmark.

Prefer Active Iterators Where Possible

---

Localization/fr-FR_Mods.Luminance.hjson

Just a small pull request to improve French translations.

French Localization Improvements

---

Core/Graphics/Automators/RenderTargetManager.cs

fix: preserve rts surrounding RenderTargetUpdateLoopEvent
